apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  labels:
    app: service-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
        version: 2.0.0
    spec:
      containers:
      - name: service-b
        image: nginxinc/nginx-unprivileged:stable # Example image
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.10.1 # Elasticsearch image
        ports:
        - containerPort: 9200 # REST API
        - containerPort: 9300 # Node communication
        env:
        - name: discovery.type
          value: single-node # Single-node mode for testing
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        volumeMounts:
        - name: es-data
          mountPath: /usr/share/elasticsearch/data

      volumes:
      - name: es-data
        emptyDir: {} # Temporary storage for Elasticsearch data
