apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
        version: 1.34.1
    spec:
      serviceAccountName: porygon-sa
      containers:
      - name: busybox
        image: busybox:1.34.1
        command: ["sh", "-c", "while true; do echo 'Service A Running'; sleep 3600; done"]
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.10.1
        ports:
        - containerPort: 9200 # REST API
        - containerPort: 9300 # Node communication
        env:
        - name: discovery.type
          value: single-node # Single-node for testing
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        volumeMounts:
        - name: es-data
          mountPath: /usr/share/elasticsearch/data

      volumes:
      - name: es-data
        emptyDir: {}
